# Generated by Django 4.2.4 on 2023-12-05 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_matches'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matches',
            old_name='sender',
            new_name='user1',
        ),
        migrations.RenameField(
            model_name='matches',
            old_name='receiver',
            new_name='user2',
        ),
    ]
