# Generated by Django 4.2.4 on 2023-12-07 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_message_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
