# Generated by Django 4.2.4 on 2023-12-10 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_message_room_message_match'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='match',
            new_name='match_id',
        ),
    ]
