# Generated by Django 4.2.4 on 2023-12-10 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_match_message_match_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='match_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='match_id', to='app.matches'),
        ),
    ]
