# Generated by Django 4.2.4 on 2023-12-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_message_match_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='match_id',
            field=models.IntegerField(),
        ),
    ]
